#cloud-config
password: ubuntu
chpasswd: { expire: false }
ssh_pwauth: true
users:
  - default
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
hostname: __HOSTNAME__
runcmd:
  - [ sh, -xc, "echo Here is the network config for your instance" ]
  - [ ip, a ]
  - [ sh, -xc, "echo =========== nameserver setup ===========" ]
  - [ sh, -xc, "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf" ]

final_message: "Cloud init is done.  Woohoo!"
